
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int CHAR_CONST = 50;
  public static final int POW = 43;
  public static final int WHEN = 35;
  public static final int CHAR = 13;
  public static final int GE = 54;
  public static final int UMINUS = 45;
  public static final int INTEGER_CONST = 48;
  public static final int INTEGER = 17;
  public static final int SEMI = 4;
  public static final int OUT = 12;
  public static final int INIT = 31;
  public static final int RBRAC = 10;
  public static final int MINUS = 37;
  public static final int FOR = 20;
  public static final int WRITE = 26;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int LT = 55;
  public static final int RPAR = 7;
  public static final int OR = 41;
  public static final int BOOL = 18;
  public static final int COMMA = 5;
  public static final int DIV = 39;
  public static final int PLUS = 36;
  public static final int LOOP = 29;
  public static final int ASSIGN = 30;
  public static final int MAIN = 2;
  public static final int IF = 22;
  public static final int WRITELN = 27;
  public static final int ID = 47;
  public static final int LE = 56;
  public static final int EOF = 0;
  public static final int RETURN = 59;
  public static final int TRUE = 51;
  public static final int error = 1;
  public static final int PIPE = 11;
  public static final int VOID = 15;
  public static final int EQ = 57;
  public static final int TIMES = 38;
  public static final int COLON = 8;
  public static final int ELSE = 24;
  public static final int READ = 25;
  public static final int TO = 21;
  public static final int WHILE = 23;
  public static final int STR_CONCAT = 44;
  public static final int FLOAT = 19;
  public static final int REAL_CONST = 49;
  public static final int THEN = 28;
  public static final int NE = 58;
  public static final int LPAR = 6;
  public static final int STRING = 14;
  public static final int DEF = 3;
  public static final int LBRAC = 9;
  public static final int FALSE = 52;
  public static final int STRING_CONST = 46;
  public static final int GT = 53;
  public static final int VAR = 16;
  public static final int ELSELOOP = 34;
  public static final int DO = 32;
  public static final int STEP = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "DEF",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "COLON",
  "LBRAC",
  "RBRAC",
  "PIPE",
  "OUT",
  "CHAR",
  "STRING",
  "VOID",
  "VAR",
  "INTEGER",
  "BOOL",
  "FLOAT",
  "FOR",
  "TO",
  "IF",
  "WHILE",
  "ELSE",
  "READ",
  "WRITE",
  "WRITELN",
  "THEN",
  "LOOP",
  "ASSIGN",
  "INIT",
  "DO",
  "STEP",
  "ELSELOOP",
  "WHEN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "AND",
  "OR",
  "NOT",
  "POW",
  "STR_CONCAT",
  "UMINUS",
  "STRING_CONST",
  "ID",
  "INTEGER_CONST",
  "REAL_CONST",
  "CHAR_CONST",
  "TRUE",
  "FALSE",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "RETURN"
  };
}

