#!/bin/bash
usage(){
	echo "USAGE: ./NewLang2C FILENAME"
	exit 1
}

if [[ $# -lt 1 ]]
then
	usage
fi



input=$1
opzioni=$2$3$4

if [[ "$opzioni" != *"-xml"* ]] && [[ "$opzioni" != *"-sp"* ]] && [[ "$opzioni" != *"-sc"* ]] && [[ "$opzioni" != "" ]]
then
	echo "Comando/i "$opzioni" non trovato/i"
fi

newlang_filename=$input
c_filename="CodiciC\\"${input%.nl}.c
xml_filename="XMLTreeCode\\"${input%.nl}.xml
outputfile=${input%.nl}

if [[ "$opzioni" == *"-xml"* ]]
then
	mkdir "XMLTreeCode"
fi


mkdir "CodiciC"

java -jar NewLang.jar $newlang_filename $opzioni
gcc $c_filename -lm -o $outputfile

if [[ "$opzioni" == *"-xml"* ]]
then
	cp -r $xml_filename  ${input%.nl}.xml
	rm -rf "XMLTreeCode"
fi

if [[ "$opzioni" == *"-sc"* ]]
then
	cp -r $c_filename ${input%.nl}.c
fi

rm -rf "CodiciC"