#!/bin/bash
usage(){
	echo "USAGE: ./NewLang2C FILENAME"
	exit 1
}

if [[ $# -lt 1 ]]
then
	usage
fi

input=$1
opzioni=$2
echo $opzioni;
newlang_filename=$input
c_filename="CodiciC\\"${input%.nl}.c
outputfile=${input%.nl}

mkdir "XMLTreeCode"
mkdir "CodiciC"

java -jar NewLang.jar $newlang_filename $opzioni
gcc $c_filename -lm -o $outputfile 

rm -rf "XMLTreeCode"
rm -rf "CodiciC"
