#!/bin/bash
usage(){
	echo "USAGE: ./NewLang2C FILENAME"
	exit 1
}

if [[ $# -lt 1 ]]
then
	usage
fi

input=$1
opzioni=$2$3$4

newlang_filename=$input
c_filename="CodiciC\\"${input%.nl}.c
outputfile=${input%.nl}

if [ "$opzioni" != *"-xml"* ] || [ "$opzioni" != *"-sp"* ] || [ "$opzioni" != *"-sc"* ]
then
	echo "Comando/i non trovato/i : "$opzioni
fi

if [[ "$opzioni" == *"-xml"* ]]
then
	mkdir "XMLTreeCode"
	cp -r XMLTreeCode\\${input%.nl}.xml ${input%.nl}.xml
fi

mkdir "CodiciC"

java -jar NewLang.jar $newlang_filename $opzioni
gcc $c_filename -lm -o $outputfile

if [[ "$opzioni" == *"-xml"* ]]
then
	rm -rf "XMLTreeCode"
fi

if [[ "$opzioni" == *"-sc"* ]]
then
	cp -r $c_filename ${input%.nl}.c
fi

rm -rf "CodiciC"